### PR TITLE
AcceptEntityInput invalid index + optmized :D

### PR DESCRIPTION
**Pull request by LuxLuma**
L 08/04/2018 - 028:26: [SM] Call stack trace:
L 08/04/2018 - 028:26: [SM] [0] AcceptEntityInput
L 08/04/2018 - 028:26: [SM] [1] Line 215, st_rock.sp::tTimerRockUpdate

https://forums.alliedmods.net/showpost.php?p=2608096&postcount=246

Please carefully review changes.

### CODE REVIEW

**Comment by LuxLuma** [comment]
I don't really know your code very well however i just follow the flow of the code.

**Comment by Psykotikism** [comment]
I'll keep this pull request open until I release the next update. You've helped me optimize a lot of the plugins for this project. Thank you!

**Comment by LuxLuma** [comment]
I'm sure you're ment to merge changes because you used 90% of them -_-

**Comment by Psykotikism** [comment]
I made other changes so they were conflicting with yours. xD

**Pull request closed without merging**
